version: "3"
services:

  database:
    image: postgres:13-alpine
    container_name: database
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 6543:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pet_shelter
    healthcheck:
      test: pg_isready -U postgres -d pet_shelter
      interval: 1s
      timeout: 500ms
      start_period: 0s
      retries: 3
    restart: unless-stopped

  application:
    build: ./backend
    container_name: application
    ports:
      - 8080:8080
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      TG_TOKEN: 6192284330:AAE_4ry-OrhcdOGjbeMTnDOxdjJgzONOVDA
    depends_on:
      database:
        condition: service_healthy

volumes:
  database-data:
